### ISSUE TITLE
mistyped CSS 

### ISSUE THREAD

**Issue by Maghil** [glynnbird/glynnbirddotcom#5]
wrong code \:

`.article{border-bottom:border-bottom:2px aolid #666}`

Correct code \:

`.article{border-bottom : 2px solid #666}`

I would have given out you a pull request but I couldn't find the class in your css files

### Who am I \:
just some one who was googling recaptcha for jekyll

**Comment by glynnbird** [comment]
Thanks :)

**Comment by glynnbird** [comment]
Fixed
